trigger:
- master

variables:
  vmImageName: MyCustomAgent
  dockerRegistryServiceConnection: bahabouali
  imageRepository: bahabouali/ppp
  containerRegistry: https://hub.docker.com/
  dockerfilePath: ./Dockerfile
  tag: '$(Build.BuildId)'

pool:
  name: MyLocalAgent
  vmImage: $(vmImageName)

stages:
  - stage: build
    displayName: Build 
    jobs:
      - job: MavenBuildThenDockerBuildAndPush
        displayName: Maven Build Then Docker Build And Push
        steps:
        - task: Maven@3
          displayName: MavenBuildAndPackage
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            codeCoverageToolOption: 'JaCoCo'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            isJacocoCoverageReportXML: true
            sqMavenPluginVersionChoice: 'latest'
            sonarQubeRunAnalysis: false
            goals: 'package'
        - task: Docker@2
          displayName: DockerBuildAndPush
          inputs:
            repository: 'https://hub.docker.com/repository/docker/bahabouali/ppp'
            command: 'buildAndPush'
            Dockerfile: 'Dockerfile'