trigger:
- master

variables:
  vmImageName: MyCustomAgent
  dockerRegistryServiceConnection: bahabouali
  imageRepository: bahabouali/ppp
  containerRegistry: https://hub.docker.com/
  dockerfilePath: ./Dockerfile
  tag: '$(Build.BuildId)'

pool:
  name: MyLocalAgent
  vmImage: $(vmImageName)

stages:
  - stage: build
    displayName: Build 
    jobs:
      - job: MavenBuildThenDockerBuildAndPush
        displayName: Maven Build Then Docker Build And Push
        steps:
        - task: Maven@3
          displayName: MavenBuildAndPackage
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            codeCoverageToolOption: 'JaCoCo'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            isJacocoCoverageReportXML: true
            sqMavenPluginVersionChoice: 'latest'
            sonarQubeRunAnalysis: false
            goals: 'package'
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker Hub connection'
            repository: 'bahabouali/ppp'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            buildContext: '.'
          env:
            DOCKER_BUILDKIT: 1
        - task: CopyFiles@2
          inputs:
            SourceFolder: '.'
            Contents: '*.yml'
            TargetFolder: $(Build.ArtifactStagingDirectory)
        - task: CopyFiles@2
          inputs:
            SourceFolder: './src/main/resources'
            Contents: '*.yml'
            TargetFolder: $(Build.ArtifactStagingDirectory)
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
        