trigger:
- master

variables:
  vmImageName: MyCustomAgent
  dockerRegistryServiceConnection: bahabouali
  imageRepository: bahabouali/ppp
  containerRegistry: https://hub.docker.com/
  dockerfilePath: ./Dockerfile
  tag: '$(Build.BuildId)'

pool:
  name: MyLocalAgent
  vmImage: $(vmImageName)

stages:
  - stage: build
    displayName: Build 
    jobs:
      - job: MavenBuildAndPackage
        displayName: Maven Build and Package Artifact
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            codeCoverageToolOption: 'JaCoCo'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            isJacocoCoverageReportXML: true
            sqMavenPluginVersionChoice: 'latest'
            sonarQubeRunAnalysis: false
            goals: 'package'
      - job: DockerBuildAndPush
        displayName: Docker Build and Push
        steps:
        - task: Docker@2
          displayName: Build and push an image to Dockerhub
          inputs:
            command: buildAndPush
            repository: $(imageRepository)
            dockerfile: $(dockerfilePath)
            containerRegistry: $(dockerRegistryServiceConnection)
            tags: |
              $(tag)