trigger:
- master

variables:
  vmImageName: PPP-pipeline-VM

stages:
  - stage: build
    displayName: Build stage
    jobs:
      - job: MavenBuildAndPackage
        displayName: Maven Build and Package Artifact
        pool:
          name: azureVM
          vmImage: $(vmImageName)
        steps:
        - task: Bash@3
          displayName: Set Maven Env variables
          inputs:
            targetType: 'inline'
            script: 'echo "##vso[task.setvariable variable=JAVA_HOME]/usr/lib/jvm/default-java" && echo "##vso[task.setvariable variable=M2_HOME]/opt/maven" && echo "##vso[task.setvariable variable=MAVEN_HOME]/opt/maven'
        - task: Bash@3
          displayName: Add Maven to path
          inputs:
            targetType: 'inline'
            script: 'echo "##vso[task.setvariable variable=PATH]$(M2_HOME/bin:$(PATH)"'
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            codeCoverageToolOption: 'JaCoCo'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            isJacocoCoverageReportXML: true
            sqMavenPluginVersionChoice: 'latest'
            sonarQubeRunAnalysis: false
            goals: 'package'